services:
  web1:
    image: "httpd:2.4"
    volumes: 
      - ./httpd-web1:/usr/local/apache2/htdocs/


  web2:
    image: "httpd:2.4"
    volumes: 
      - ./httpd-web2:/usr/local/apache2/htdocs/

  reverse:
    image: "nginx:1.25"
    volumes:
      - ./nginx-reverse/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-reverse/ssl:/etc/nginx/ssl
    ports: 
      - "443:443"
      - "80:80"
